# Build settings
plugins:
  - jemoji
  - jekyll-paginate-v2

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - init_server.sh
  - init_dev_server.sh
  - init_algolia_index.sh
  - _algolia_api_key
  - _algolia_api_key.sample

# Dependencies
markdown:         kramdown
highlighter:      rouge # changed from `pygments` as github says so
version: 0.1
show_drafts: false

# Algolia
algolia:
  application_id: 99NYQNU15U
  index_name: machine_learning_medium
  search_only_api_key: c1a81c44a486ccb7fb3e44114bf37b26

# Permalinks
permalink: /:year/:month/:day/:title/

# Site settings
title: "Machine Learning Medium"
description: A step away from the illusion of knowledge.
cover: "/assets/images/cover.jpg"
footer: "/assets/images/footer.jpg"
url: "https://machinelearningmedium.com"
facebook_page: "https://www.facebook.com/machinelearningmedium/"
facebook_app_id: 391866664565981
baseurl: ""
google_analytics: UA-108148924-1
vicomi: 334e9d2a5dc341469cda15d8c4bd935e

# Tags in sectionbar
category:
  - machine-learning: Machine Learning
  - mathematics: Mathematics
  - papers: Papers

# Collections to Highlight
collection:
  - title: Basics of Machine Learning
    description: Inspired by the Machine Learning lectures by Andrew Ng at Coursera, this is a beginner series that provides a broad introduction to machine learning, datamining, and statistical pattern recognition.
    url: basics-of-machine-learning
    cover: "/assets/images/basics-of-machine-learning.jpg"

  - title: What is Mathematics?
    description: A series of posts to consolidate the ideas in the famous book "What is Mathematics?" by R. Courant which gives lucid representation of the fundamental concepts and methods of the field.
    url: what-is-mathematics
    cover: "/assets/images/what-is-mathematics.jpg"

  - title: Basics of Computer Vision
    description: Summary of the course on Udacity, "Introduction to Computer Vision". Introduces fundamentals of image formation, noise, filtering, feature detection, classification etc.
    url: basics-of-computer-vision
    cover: "/assets/images/basics-of-computer-vision.jpg"

  - title: "NPTEL: Computer Architecture"
    description: Offered by NPTEL, this course is a dive into theoretical computer science introducing the software and hardware aspects of a computer organization in terms of instruction execution and design implementations.
    url: nptel-computer-architecture
    cover: "/assets/images/computer-architecture.jpg"


# Pagination using jekyll-paginate-v2
pagination:
  enabled: true
  debug: false
  collection: 'posts'
  per_page: 9
  permalink: '/:num/'
  title: ':title - Page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  tag: ''
  locale: ''
  trail: 
    before: 1
    after: 1

# Generate links for all tags
autopages:
  enabled: true
  categories: 
    layouts:
      - 'autopage_categories.html'
    title: ':cat Series'
    permalink: '/collection/:cat'
  tags:
    layouts: 
      - 'autopage_tags.html'
    title: 'Tagged In: :tag'
    permalink: '/tag/:tag'
  collections:
    enabled: false

# Author Info
author:
  name: 'Shams S'
  email: shams.sam@live.com
  description: 'Data Scientist @ Practo'
  image: "/assets/images/author.jpg"
  twitter_handle: '@sshamssam'
  twitter_url: 'https://twitter.com/sshamssam'
  disqus: shams-sam

# Social icons and sharing options
social:
  - icon: github-alt
    url:  https://github.com/shams-sam/shams-sam.github.io
    desc: Gihub Project
    share_url:
    share_title:
    share_link:

  - icon: facebook
    url:  https://facebook.com/shams-sam
    desc: Facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	twitter
    url:	https://twitter.com/sshamssam
    desc: Twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon: linkedin
    url:  https://linkedin.com/in/shams-sheikh-20328154
    desc: LinkedIn
    share_url:
    share_title:
    share_link:

  - icon: envelope
    url: "mailto:shams.sam@live.com"
    desc: E-mail
    share_url:
    share_title:
    share_link:
